title: "MY HOMEPAGE!"
logo: /assets/img/hippo.jpg
description: "Welcome to my homepage!"
theme: null

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

# Navigation (used by Minimal's header)
# Comment out if you want no header links
header_pages:
  - about.md
  - projects.md

# Optional: GitHub repo link in footer
github:
  username: "mlng7squared"
